### ISSUE TITLE
Ambilight Mode

### ISSUE THREAD

**Issue by Crajs20** [AlCalzone/ioBroker.philips-tv#431]
Hi,

1st thanks for the great adapter, works well.

I using the adapter to control the ambilight and turn it automatically off during the day and back on in the evening.
I have the Abilight video mode setup to default.
When I turn ambilght off and back on, its set to "Spiele" - Games, not to the old value -default.

How this can be changed, I thought I can change the profile with philips-tv.0.settings.customAmbilightCommand, but was not able to do.
I checked the value of philips-tv.0.settings.customAmbilightCommand, but this doesnt change if I change the ambilight profile.

How I can change the ambilight profile or leave the profile as it is and just turn it off and on?

**Comment by foxriver76** [comment]
Currently you can achieve this via the `customAmbilightCommand` datapoint. The default value provides an example.

**Comment by patrickbs96** [comment]
@Crajs20 If you are still looking für the options which can be set here. [Here](https://github.com/eslavnov/pylips/blob/master/available_commands.json#L49-L221) is a list of all the current commands.
You just need to copy the body into `customAmbilightCommand`.

@foxriver76 Wouldn't it make sense to add polling to `ambilight/currentconfiguration` so that the active ambilight setting is always visible to the user? Or maybe add another state in which all the options are available so the user doesn't need to work with the json string at all.
I'd be happy to create the pull requests in both repos but I'm not sure how to link them as you are currently referencing a specific commit. Or will you update that afterwards?

**Comment by foxriver76** [comment]
Yes, makes sense. I haven’t had time to think about a convenient solution, as there are also more customized commands than listed in the referenced code. 

The polling makes sense, we just need support in Lib first but that’s no problem.

**Comment by foxriver76** [comment]
Please check 0.5.2 with `currentAmbilightConfiguration` and delete the state `customAmbilightCommand` manually (sorry pre v1 version). The state now gets synced so you can look up the current config.

**Comment by foxriver76** [comment]
> I'd be happy to create the pull requests in both repos but I'm not sure how to link them as you are currently referencing a specific commit. Or will you update that afterwards?

Yes, currently the development is in my fork of the lib on the `iob` branch. So thus instead of updating versions, I reference a specific commit. I think about making it an own npm package, as the maintainer of the original lib is non-responsive for months. If you have a good idea how to make the ambilight states more user friendly or other optimizations, feel free to create PRs against my fork of the lib as well as the adapter.
